Repository nheyland/MyWeek, pull requests merged in 2021-03, with the labels that each got.

#39 The Tell Everyone Update!
  db.sqlite3
  login/__pycache__/__init__.cpython-38.pyc
  login/__pycache__/models.cpython-38.pyc
  login/__pycache__/render.cpython-38.pyc
  login/__pycache__/urls.cpython-38.pyc
  login/__pycache__/views.cpython-38.pyc
  login/migrations/__pycache__/0001_initial.cpython-38.pyc
  login/migrations/__pycache__/0001_initial.cpython-39.pyc
  login/migrations/__pycache__/0002_friends.cpython-39.pyc
  login/migrations/__pycache__/0003_auto_20210225_1318.cpython-39.pyc
  login/migrations/__pycache__/0004_auto_20210225_2213.cpython-39.pyc
  login/migrations/__pycache__/0005_auto_20210225_2235.cpython-39.pyc
  login/migrations/__pycache__/0006_auto_20210225_2350.cpython-39.pyc
  login/migrations/__pycache__/0007_auto_20210226_0007.cpython-39.pyc
  login/migrations/__pycache__/__init__.cpython-38.pyc
  login/migrations/__pycache__/__init__.cpython-39.pyc
  planner/__pycache__/__init__.cpython-38.pyc
  planner/__pycache__/admin.cpython-38.pyc
  planner/__pycache__/geocode.cpython-38.pyc
  planner/__pycache__/models.cpython-38.pyc
  planner/__pycache__/time_return.cpython-39.pyc
  planner/__pycache__/urls.cpython-38.pyc
  planner/__pycache__/utils.cpython-38.pyc
  planner/__pycache__/views.cpython-38.pyc
  planner/migrations/__pycache__/0001_initial.cpython-38.pyc
  planner/migrations/__pycache__/0001_initial.cpython-39.pyc
  planner/migrations/__pycache__/0002_auto_20210225_0342.cpython-38.pyc
  planner/migrations/__pycache__/0002_auto_20210225_0342.cpython-39.pyc
  planner/migrations/__pycache__/0003_event_address.cpython-38.pyc
  planner/migrations/__pycache__/0003_event_address.cpython-39.pyc
  planner/migrations/__pycache__/0004_remove_event_date.cpython-38.pyc
  planner/migrations/__pycache__/0004_remove_event_date.cpython-39.pyc
  planner/migrations/__pycache__/0005_event_invitees.cpython-39.pyc
  planner/migrations/__pycache__/__init__.cpython-38.pyc
  planner/migrations/__pycache__/__init__.cpython-39.pyc
  planner/models.py
  planner/templates/details.html
  planner/urls.py
  planner/views.py
  requirements.txt
  social/templates/social/confirm_delete.html
  social/urls.py
  social/util.py
  social/views.py
Labels: enhancement

#41 Adjusting Sidebar to be interactive
  planner/static/css/style.css
  planner/static/css/style.css.map
  planner/static/css/style.scss
  planner/templates/planner.html
  planner/utils.py
Labels: enhancement

#80 Template Bug Fix
  planner/templates/details.html
Labels: bug

#81 Minor 'For Live' Update
  myWeek/settings.py
  social/views.py
Labels: Deployment
